name: Call a reusable Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version to start'
        required: true

jobs:
  build:
    uses: Bombaharris/github-actions-reusable/.github/workflows/release.yml@master
    permissions:
      contents: write
      packages: write
      pull-requests: write
    with:
        VERSION: ${{ github.event.inputs.version }}
    secrets: inherit
